#!/usr/bin/env sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################
set -e
APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -Dorg.gradle.appname="$(basename "$0")" \
  -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
